#!/usr/bin/env python3
"""Generate Chinese name mappings for Pokemon and moves."""

import json
import os

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")

# Common Pokemon Chinese names (most popular ones)
POKEMON_CN = {
    # Gen 1
    "Bulbasaur": "妙蛙种子", "Ivysaur": "妙蛙草", "Venusaur": "妙蛙花",
    "Charmander": "小火龙", "Charmeleon": "火恐龙", "Charizard": "喷火龙",
    "Squirtle": "杰尼龟", "Wartortle": "卡咪龟", "Blastoise": "水箭龟",
    "Caterpie": "绿毛虫", "Metapod": "铁甲蛹", "Butterfree": "巴大蝶",
    "Weedle": "独角虫", "Kakuna": "铁壳蛹", "Beedrill": "大针蜂",
    "Pidgey": "波波", "Pidgeotto": "比比鸟", "Pidgeot": "大比鸟",
    "Rattata": "小拉达", "Raticate": "拉达",
    "Spearow": "烈雀", "Fearow": "大嘴雀",
    "Ekans": "阿柏蛇", "Arbok": "阿柏怪",
    "Pikachu": "皮卡丘", "Raichu": "雷丘",
    "Sandshrew": "穿山鼠", "Sandslash": "穿山王",
    "Nidoran♀": "尼多兰", "Nidorina": "尼多娜", "Nidoqueen": "尼多后",
    "Nidoran♂": "尼多朗", "Nidorino": "尼多力诺", "Nidoking": "尼多王",
    "Clefairy": "皮皮", "Clefable": "皮可西",
    "Vulpix": "六尾", "Ninetales": "九尾",
    "Jigglypuff": "胖丁", "Wigglytuff": "胖可丁",
    "Zubat": "超音蝠", "Golbat": "大嘴蝠",
    "Oddish": "走路草", "Gloom": "臭臭花", "Vileplume": "霸王花",
    "Paras": "派拉斯", "Parasect": "派拉斯特",
    "Venonat": "毛球", "Venomoth": "摩鲁蛾",
    "Diglett": "地鼠", "Dugtrio": "三地鼠",
    "Meowth": "喵喵", "Persian": "猫老大",
    "Psyduck": "可达鸭", "Golduck": "哥达鸭",
    "Mankey": "猴怪", "Primeoke": "火暴猴",
    "Growlithe": "卡蒂狗", "Arcanine": "风速狗",
    "Poliwag": "蚊香蝌蚪", "Poliwhirl": "蚊香君", "Poliwrath": "蚊香泳士",
    "Abra": "凯西", "Kadabra": "勇基拉", "Alakazam": "胡地",
    "Machop": "腕力", "Machoke": "豪力", "Machamp": "怪力",
    "Bellsprout": "喇叭芽", "Weepinbell": "口呆花", "Victreebel": "大食花",
    "Tentacool": "玛瑙水母", "Tentacruel": "毒刺水母",
    "Geodude": "小拳石", "Graveler": "隆隆石", "Golem": "隆隆岩",
    "Ponyta": "小火马", "Rapidash": "烈焰马",
    "Slowpoke": "呆呆兽", "Slowbro": "呆壳兽",
    "Magnemite": "小磁怪", "Magneton": "三合一磁怪",
    "Farfetch'd": "大葱鸭", "Doduo": "嘟嘟", "Dodrio": "嘟嘟利",
    "Seel": "白海狮", "Dewgong": "刺甲海狮",
    "Grimer": "臭泥", "Muk": "臭臭泥",
    "Shellder": "大舌贝", "Cloyster": "刺甲贝",
    "Gastly": "鬼斯", "Haunter": "鬼斯通", "Gengar": "耿鬼",
    "Onix": "大岩蛇", "Drowzee": "催眠貘", "Hypno": "引梦貘人",
    "Krabby": "大钳蟹", "Kingler": "巨钳蟹",
    "Voltorb": "霹雳电球", "Electrode": "顽皮雷弹",
    "Exeggcute": "蛋蛋", "Exeggutor": "椰蛋树",
    "Cubone": "卡拉卡拉", "Marowak": "嘎啦嘎啦",
    "Hitmonlee": "飞腿郎", "Hitmonchan": "快拳郎",
    "Lickitung": "大舌头", "Koffing": "瓦斯弹", "Weezing": "双弹瓦斯",
    "Rhyhorn": "独角犀牛", "Rhydon": "钻角犀兽",
    "Chansey": "吉利蛋", "Tangela": "蔓藤怪", "Kangaskhan": "袋兽",
    "Horsea": "墨海马", "Seadra": "海刺龙",
    "Goldeen": "角金鱼", "Seaking": "金鱼王",
    "Staryu": "海星星", "Starmie": "宝石海星",
    "Mr. Mime": "魔墙人偶", "Scyther": "飞天螳螂",
    "Jynx": "迷唇姐", "Electabuzz": "电击兽", "Magmar": "鸭嘴火兽",
    "Pinsir": "凯罗斯", "Tauros": "肯泰罗",
    "Magikarp": "鲤鱼王", "Gyarados": "暴鲤龙",
    "Lapras": "拉普拉斯", "Ditto": "百变怪",
    "Eevee": "伊布", "Vaporeon": "水伊布", "Jolteon": "雷伊布", "Flareon": "火伊布",
    "Porygon": "多边兽", "Omanyte": "菊石兽", "Omastar": "多刺菊石兽",
    "Kabuto": "化石盔", "Kabutops": "镰刀盔",
    "Aerodactyl": "化石翼龙", "Snorlax": "卡比兽",
    "Articuno": "急冻鸟", "Zapdos": "闪电鸟", "Moltres": "火焰鸟",
    "Dratini": "迷你龙", "Dragonair": "哈克龙", "Dragonite": "快龙",
    "Mewtwo": "超梦", "Mew": "梦幻",
    
    # Gen 2
    "Chikorita": "菊草叶", "Bayleef": "月桂叶", "Meganium": "大竺葵",
    "Cyndaquil": "火球鼠", "Quilava": "火岩鼠", "Typhlosion": "火暴兽",
    "Totodile": "小锯鳄", "Croconaw": "蓝鳄", "Feraligatr": "大力鳄",
    "Sentret": "尾立", "Furret": "大尾立",
    "Hoothoot": "咕咕", "Noctowl": "猫头夜鹰",
    "Ledyba": "瓢虫", "Ledian": "七星瓢虫",
    "Spinarak": "圆丝蛛", "Ariados": "阿利多斯",
    "Crobat": "叉字蝠",
    "Chinchou": "灯笼鱼", "Lanturn": "电灯怪",
    "Pichu": "皮丘", "Cleffa": "皮宝宝", "Igglybuff": "宝宝丁",
    "Togepi": "波克比", "Togetic": "波克基古",
    "Natu": "天然雀", "Xatu": "天然鸟",
    "Mareep": "咩利羊", "Flaaffy": "茸茸羊", "Ampharos": "电龙",
    "Bellossom": "美丽花", "Marill": "玛力露", "Azumarill": "玛力露丽",
    "Sudowoodo": "树才怪", "Politoed": "蚊香蛙皇",
    "Hoppip": "毽子草", "Skiploom": "毽子花", "Jumpluff": "毽子棉",
    "Aipom": "长尾怪手",
    "Sunkern": "向日种子", "Sunflora": "向日花怪",
    "Yanma": "蜻蜓龙",
    "Wooper": "乌波", "Quagsire": "沼王",
    "Espeon": "太阳伊布", "Umbreon": "月亮伊布",
    "Murkrow": "黑暗鸦", "Slowking": "呆呆王",
    "Misdreavus": "梦妖",
    "Unown": "未知图腾",
    "Wobbuffet": "果然翁", "Girafarig": "麒麟奇",
    "Pineco": "榛果球", "Forretress": "佛烈托斯",
    "Dunsparce": "土龙弟弟",
    "Gligar": "天蝎",
    "Steelix": "大钢蛇",
    "Snubbull": "布鲁", "Granbull": "布鲁皇",
    "Qwilish": "千针鱼",
    "Scizor": "巨钳螳螂",
    "Shuckle": "壶壶",
    "Heracross": "赫拉克罗斯",
    "Sneasel": "狃拉",
    "Teddiursa": "熊宝宝", "Ursaring": "圈圈熊",
    "Slugma": "小炭犬", "Magcargo": "熔岩兽",
    "Swinub": "小山猪", "Piloswine": "长毛猪",
    "Corsola": "太阳珊瑚",
    "Remoraid": "铁炮鱼", "Octillery": "章鱼桶",
    "Delibird": "信使鸟",
    "Mantine": "乘龙", "Skarmory": "盔甲鸟",
    "Houndour": "戴鲁比", "Houndoom": "黑鲁加",
    "Kingdra": "刺龙王",
    "Phanpy": "小小象", "Donphan": "顿甲",
    "Porygon2": "多边兽II",
    "Stantler": "惊角鹿",
    "Smeargle": "图图犬",
    "Miltank": "奶牛", "Blissey": "幸福蛋",
    "Raikou": "雷公", "Entei": "炎帝", "Suicune": "水君",
    "Larvitar": "幼基拉斯", "Pupitar": "沙基拉斯", "Tyranitar": "班基拉斯",
    "Lugia": "洛奇亚", "Ho-Oh": "凤王",
    "Celebi": "时拉比",
    
    # Gen 3
    "Treecko": "木守宫", "Grovyle": "森林蜥蜴", "Sceptile": "蜥蜴王",
    "Torchic": "火稚鸡", "Combusken": "力壮鸡", "Blaziken": "火焰鸡",
    "Mudkip": "水跃鱼", "Marshtomp": "沼跃鱼", "Swampert": "巨沼怪",
    "Poochyena": "土狼犬", "Mightyena": "大狼犬",
    "Zigzagoon": "蛇纹熊", "Linoone": "直冲熊",
    "Wurmple": "刺尾虫", "Silcoon": "甲壳茧", "Beautifly": "毒粉蝶",
    "Cascoon": "盾甲茧", "Dustox": "狩猎凤蝶",
    "Lotad": "莲叶童子", "Lombre": "莲帽鸭", "Ludicolo": "乐天河童",
    "Seedot": "橡实果", "Nuzleaf": "长鼻叶", "Shiftry": "斗笠怪",
    "Taillow": "傲骨燕", "Swellow": "大王燕",
    "Wingull": "长翅鸥", "Pelipper": "大嘴鸥",
    "Ralts": "拉鲁拉丝", "Kirlia": "奇鲁莉安", "Gardevoir": "沙奈朵",
    "Surskit": "溜溜糖球", "Masquerain": "雨翅蛾",
    "Shroomish": "蘑菇孢子", "Breloom": "斗笠菇",
    "Slakoth": "懒人獭", "Vigoroth": "过动猿", "Slaking": "请假王",
    "Nincada": "土居忍士", "Ninjask": "铁面忍者", "Shedinja": "脱壳忍者",
    "Whismur": "咕妞妞", "Loudred": "吼爆弹", "Exploud": "爆音怪",
    "Makuhita": "幕下力士", "Hariyama": "超力王",
    "Azurill": "露力丽",
    "Nosepass": "朝北鼻",
    "Skitty": "向尾喵", "Delcatty": "优雅猫",
    "Sableye": "勾魂眼",
    "Mawile": "大嘴娃",
    "Aron": "可可多拉", "Lairon": "可多拉", "Aggron": "波士可多拉",
    "Meditite": "恰雷姆", "Medicham": "超级恰雷姆",
    "Electrike": "落雷兽", "Manectric": "雷电兽",
    "Plusle": "正电拍拍", "Minun": "负电拍拍",
    "Volbeat": "电萤虫", "Illumise": "甜甜萤",
    "Roselia": "毒蔷薇",
    "Gulpin": "吞食兽", "Swalot": "毒藻龙",
    "Carvanha": "牙牙", "Sharpedo": "巨牙鲨",
    "Wailmer": "吼吼鲸", "Wailord": "吼鲸王",
    "Numel": "呆火驼", "Camerupt": "喷火驼",
    "Torkoal": "煤炭龟",
    "Spoink": "跳跳猪", "Grumpig": "噗噗猪",
    "Spinda": "斑斑马",
    "Trapinch": "超音波幼虫", "Vibrava": "沙漠蜻蜓", "Flygon": "沙漠蜻蜓",
    "Cacnea": "刺球仙人掌", "Cacturne": "梦歌仙人掌",
    "Swablu": "青绵鸟", "Altaria": "七夕青鸟",
    "Zangoome": "猫鼬斩", "Seviper": "饭匙蛇",
    "Lunatone": "月石", "Solrock": "太阳岩",
    "Barboach": "泥泥鳅", "Whiscash": "鲶鱼王",
    "Corphish": "铁螯龙虾", "Crawdaunt": "铁螯龙虾",
    "Baltoy": "天蝎", "Claydol": "念力土偶",
    "Lileep": "触手百合", "Cradily": "摇篮百合",
    "Anorith": "太古羽虫", "Armaldo": "太古盔甲",
    "Feebas": "丑丑鱼", "Milotic": "美纳斯",
    "Castform": "漂浮泡泡",
    "Kecleon": "变色龙",
    "Shuppet": "诅咒娃娃", "Banette": "诅咒娃娃",
    "Duskull": "夜巡灵", "Dusclops": "彷徨夜灵",
    "Tropius": "热带龙",
    "Chimecho": "风铃铃",
    "Absol": "阿勃梭鲁",
    "Wynaut": "小果然",
    "Snorunt": "雪童子", "Glalie": "冰鬼护",
    "Spheal": "海豹球", "Sealeo": "海魔狮", "Walrein": "帝牙海狮",
    "Clamperl": "珍珠贝", "Huntail": "猎斑鱼", "Gorebyss": "樱花鱼",
    "Relicanth": "古空棘鱼",
    "Luvdisc": "爱心鱼",
    "Bagon": "宝贝龙", "Shelgon": "甲壳龙", "Salamence": "暴飞龙",
    "Beldum": "铁哑铃", "Metang": "金属怪", "Metagross": "巨金怪",
    "Regirock": "雷吉洛克", "Regice": "雷吉艾斯", "Registeel": "雷吉斯奇鲁",
    "Latias": "拉帝亚斯", "Latios": "拉帝欧斯",
    "Kyogre": "盖欧卡", "Groudon": "固拉多", "Rayquaza": "裂空座",
    "Jirachi": "基拉祈", "Deoxys": "代欧奇希斯",
    
    # Gen 4
    "Turtwig": "草苗龟", "Grotle": "树林龟", "Torterra": "土台龟",
    "Chimchar": "小火焰猴", "Monferno": "猛火猴", "Infernape": "烈焰猴",
    "Piplup": "波加曼", "Prinplup": "波皇子", "Empoleon": "帝王拿波",
    "Starly": "姆克儿", "Staravia": "姆克鸟", "Staraptor": "姆克鹰",
    "Bidoof": "大牙狸", "Bibarel": "大尾狸",
    "Kricketot": "圆法师", "Kricketune": "音箱蟀",
    "Shinx": "小猫怪", "Luxio": "勒克猫", "Luxray": "伦琴猫",
    "Budew": "含羞苞", "Roserade": "罗丝雷朵",
    "Cranidos": "头盖龙", "Rampardos": "战槌龙",
    "Shieldon": "护城龙", "Bastiodon": "护国龙",
    "Burmy": "结草儿", "Wormadam": "结草贵妇", "Mothim": "绅士蛾",
    "Combee": "三蜜蜂", "Vespiquen": "蜂女王",
    "Pachirisu": "帕奇利兹",
    "Buizel": "泳圈鼬", "Floatzel": "浮鼬王",
    "Cherubi": "桃花", "Cherrim": "甜冷美后",
    "Shellos": "无壳海兔", "Gastrodon": "海兔兽",
    "Ambipom": "双尾怪手",
    "Drifloon": "飘飘球", "Drifblim": "随风球",
    "Buneary": "卷卷耳", "Lopunny": "长耳兔",
    "Mismagius": "梦妖魔",
    "Honchkrow": "乌鸦头头",
    "Glameow": "魅力喵", "Purugly": "东施喵",
    "Chingling": "铃铛响",
    "Stunky": "臭鼬噗", "Skuntank": "坦克臭鼬",
    "Bronzor": "铜镜怪", "Bronzong": "青铜钟",
    "Bonsly": "盆才怪", "Mime Jr.": "魔尼尼",
    "Happiny": "小福蛋",
    "Chatot": "聒噪鸟",
    "Spiritomb": "花岩怪",
    "Gible": "圆陆鲨", "Gabite": "尖牙陆鲨", "Garchomp": "烈咬陆鲨",
    "Munchlax": "小卡比兽",
    "Riolu": "利欧路", "Lucario": "路卡利欧",
    "Hippopotas": "河马兽", "Hippowdon": "河马兽",
    "Skorupi": "钳尾蝎", "Drapion": "龙王蝎",
    "Croagunk": "不良蛙", "Toxicroak": "毒骷蛙",
    "Carnivine": "尖牙笼",
    "Finneon": "荧光鱼", "Lumineon": "霓虹鱼",
    "Mantyke": "小球飞鱼",
    "Snover": "树才怪", "Abomasnow": "暴雪王",
    "Weavile": "玛狃拉",
    "Magnezone": "自爆磁怪",
    "Lickilicky": "大舌舔",
    "Rhyperior": "超甲狂犀",
    "Tangrowth": "巨蔓藤",
    "Electivire": "电击魔兽",
    "Magmortar": "鸭嘴炎兽",
    "Togekiss": "波克基斯",
    "Yanmega": "远古巨蜓",
    "Leafeon": "叶伊布",
    "Glaceon": "冰伊布",
    "Gliscor": "天蝎王",
    "Mamoswine": "象牙猪",
    "Porygon-Z": "多边兽Z",
    "Gallade": "艾路雷朵",
    "Probopass": "大朝北鼻",
    "Dusknoir": "黑夜魔灵",
    "Froslass": "雪妖女",
    "Rotom": "洛托姆",
    "Uxie": "由克希", "Mesprit": "艾姆利多", "Azelf": "亚克诺姆",
    "Dialga": "帝牙卢卡", "Palkia": "帕路奇亚",
    "Heatran": "席多蓝恩",
    "Regigigas": "雷吉奇卡斯",
    "Giratina": "骑拉帝纳",
    "Cresselia": "克雷色利亚",
    "Phione": "霏欧纳", "Manaphy": "玛纳霏",
    "Darkrai": "达克莱伊",
    "Shaymin": "谢米",
    "Arceus": "阿尔宙斯",
    
    # Gen 5 (partial - most popular)
    "Victini": "比克提尼",
    "Serperior": "君主蛇",
    "Emboar": "炎武王",
    "Samurott": "大剑鬼",
    "Watchog": "步哨鼠",
    "Stoutland": "长毛狗",
    "Liepard": "酷豹",
    "Simisear": "爆香猴",
    "Simipour": "冷水猴",
    "Munna": "食梦梦", "Musharna": "梦梦蚀",
    "Pidove": "豆豆鸽", "Tranquill": "咕咕鸽", "Unfezant": "高傲雉鸡",
    "Blitzle": "斑马", "Zebstrika": "雷斑马",
    "Roggenrola": "石丸子", "Boldore": "地幔岩", "Gigalith": "庞岩怪",
    "Sawk": "修缮老头",
    "Throh": "投摔鬼",
    "Sewaddle": "虫宝包", "Swadloon": "虫甲壳", "Leavanny": "保姆虫",
    "Venipede": "百足蜈蚣", "Whirlipede": "车轮球", "Scolipede": "蜈蚣王",
    "Cottonee": "木棉球", "Whimsicott": "风妖精",
    "Petilil": "百合根娃娃", "Lilligant": "裙儿小姐",
    "Basculin": "蓝鲈鱼",
    "Sandile": "黑眼鳄", "Krokorok": "混混鳄", "Krookodile": "流氓鳄",
    "Darumaka": "火红不倒翁", "Darmanitan": "达摩狒狒",
    "Maractus": "仙人掌",
    "Dwebble": "石居蟹", "Crustle": "岩居蟹",
    "Scrafty": "头巾混混",
    "Sigilyph": "象征鸟",
    "Yamask": "死神棺", "Cofagrigus": "死神板",
    "Tirtouga": "原盖海龟", "Carracosta": "肋骨海龟",
    "Archen": "始祖小鸟", "Archeops": "始祖大鸟",
    "Trubbish": "破破袋", "Garbodor": "灰尘山",
    "Zorua": "索罗亚", "Zoroark": "索罗亚克",
    "Minccino": "泡沫栗鼠", "Cinccino": "奇诺栗鼠",
    "Gothita": "哥特宝宝", "Gothorita": "哥特少女", "Gothitelle": "哥特小姐",
    "Solosis": "单卵细胞球", "Duosion": "双卵细胞球", "Reuniclus": "人造细胞卵",
    "Ducklett": "鸭宝宝", "Swanna": "舞天鹅",
    "Vanillite": "迷你冰", "Vanillish": "多多冰", "Vanilluxe": "双倍多多冰",
    "Deerling": "四季鹿", "Sawsbuck": "四季鹿",
    "Emolga": "电飞鼠",
    "Karrablast": "盖盖虫", "Escavalier": "骑士蜗牛",
    "Foongus": "嘿咻", "Amoonguss": "败露球菇",
    "Frillish": "轻飘飘", "Jellicent": "胖嘟嘟",
    "Alomomola": "保母曼波",
    "Joltik": "电电虫", "Galvantula": "电蜘蛛",
    "Ferroseed": "种子铁球", "Ferrothorn": "坚果哑铃",
    "Klink": "齿轮儿", "Klang": "齿轮组", "Klinklang": "齿轮怪",
    "Tynamo": "麻麻小鱼", "Eelektrik": "麻麻鳗", "Eelektross": "麻麻鳗鱼王",
    "Elgyem": "小灰怪", "Beheeyem": "大宇怪",
    "Litwick": "烛光灵", "Lampent": "灯火幽灵", "Chandelure": "水晶灯火灵",
    "Axew": "牙牙", "Fraxure": "斧牙龙", "Haxorus": "双斧战龙",
    "Cubchoo": "喷嚏熊", "Beartic": "冻原熊",
    "Shelmet": "小嘴蜗", "Accelgor": "敏捷虫",
    "Stunfisk": "泥巴鱼",
    "Mienfoo": "功夫鼬", "Mienshao": "师父鼬",
    "Druddigon": "赤面龙",
    "Golett": "泥偶小人", "Golurk": "泥偶巨人",
    "Bouffalant": "野牦牛",
    "Rufflet": "毛头小鹰", "Braviary": "秃鹰娜",
    "Vullaby": "秃鹰丫头", "Mandibuzz": "秃鹰王",
    "Heatmor": "熔蚁兽", "Durant": "铁蚁",
    "Deino": "单首龙", "Zweilous": "双首暴龙", "Hydreigon": "三首恶龙",
    "Larvesta": "燃烧虫", "Volcarona": "火神蛾",
    "Cobalion": "勾帕路翁", "Terrakion": "代拉基翁", "Virizion": "毕力吉翁",
    "Tornadus": "龙卷云", "Thundurus": "雷电云", "Landorus": "土地云",
    "Reshiram": "莱希拉姆", "Zekrom": "捷克罗姆",
    "Kyurem": "酋雷姆",
    "Keldeo": "凯路迪欧",
    "Meloetta": "美洛耶塔",
    "Genesect": "盖诺赛克特",
    
    # Gen 6
    "Chesnaught": "布里卡隆", "Delphox": "妖火红狐", "Greninja": "甲贺忍蛙",
    "Talonflame": "烈箭鹰", "Vivillon": "彩粉蝶",
    "Pangoro": "流氓熊猫", "Meowstic": "超能妙喵",
    "Aegislash": "坚盾剑怪", "Slurpuff": "胖甜妮",
    "Malamar": "超坏星", "Barbaracle": "爪爪乐", "Dragalge": "毒藻龙",
    "Clauncher": "铁臂枪虾", "Clawitzer": "加农炮虾",
    "Hawlucha": "摔角鹰人", "Dedenne": "咚咚鼠",
    "Carbink": "小碎钻", "Goomy": "黏黏宝", "Sliggoo": "黏美儿", "Goodra": "黏美龙",
    "Klefki": "钥圈儿", "Phantump": "朽木妖", "Trevenant": "朽木妖",
    "Pumpkaboo": "南瓜精", "Gourgeist": "南瓜怪人",
    "Bergmite": "冰宝", "Avalugg": "冰岩怪",
    "Noibat": "嗡蝠", "Noivern": "音波龙",
    "Xerneas": "哲尔尼亚斯", "Yveltal": "伊裴尔塔尔", "Zygarde": "基格尔德",
    "Diancie": "蒂安希", "Hoopa": "胡帕", "Volcanion": "波尔凯尼恩",
    
    # Gen 7
    "Decidueye": "狙射树枭", "Incineroar": "炽焰咆哮虎", "Primarina": "西狮海壬",
    "Pikipek": "小笃儿", "Trumbeak": "喇叭雏鸟", "Toucannon": "铳嘴大鸟",
    "Yungoos": "猫鼬少", "Gumshoos": "猫鼬探长",
    "Grubbin": "强颚鸡母虫", "Charjabug": "虫电宝", "Vikavolt": "锹农炮虫",
    "Crabrawler": "好胜蟹", "Crabominable": "好胜毛蟹",
    "Oricorio": "花舞鸟",
    "Cutiefly": "萌虻", "Ribombee": "蝶蝶萌虻",
    "Rockruff": "岩狗狗", "Lycanroc": "鬃岩狼人",
    "Wishiwashi": "弱丁鱼",
    "Mareanie": "超坏星", "Toxapex": "超坏星",
    "Mudbray": "泥驴仔", "Mudsdale": "重泥挽马",
    "Dewpider": "滴蛛", "Araquanid": "滴蛛霸",
    "Fomantis": "伪螳草", "Lurantis": "兰螳花",
    "Morelull": "萌萌哒", "Shiinotic": "伞电蜥",
    "Salandit": "夜盗火蜥", "Salazzle": "焰后蜥",
    "Stufful": "穿着熊", "Bewear": "穿着熊",
    "Bounsweet": "甜竹竹", "Steenee": "甜舞妮", "Tsareena": "甜冷美后",
    "Comfey": "花疗环环",
    "Oranguru": "智挥猩", "Passimian": "投掷猴",
    "Wimpod": "胆小虫", "Golisopod": "具甲武者",
    "Sandygast": "沙丘娃", "Palossand": "噬沙堡爷",
    "Pyukumuku": "拳海参",
    "Type: Null": "属性：空", "Silvally": "银伴战兽",
    "Minior": "小陨星",
    "Komala": "树枕尾熊",
    "Turtonator": "爆焰龟兽",
    "Mimikyu": "谜拟Q",
    "Bruxish": "磨牙彩皮鱼",
    "Drampa": "老翁龙",
    "Dhelmise": "破舵轮",
    "Jangmo-o": "心鳞宝", "Hakamo-o": "鳞甲龙", "Kommo-o": "杖尾鳞甲龙",
    "Tapu Koko": "卡璞・鸣鸣", "Tapu Lele": "卡璞・蝶蝶",
    "Tapu Bulu": "卡璞・哞哞", "Tapu Fini": "卡璞・鳍鳍",
    "Cosmog": "科斯莫古", "Cosmoem": "科斯莫姆",
    "Solgaleo": "索尔迦雷欧", "Lunala": "露奈雅拉",
    "Nihilego": "虚吾伊德", "Buzzwole": "爆肌蚊",
    "Pheromosa": "费洛美螂", "Xurkitree": "电束木",
    "Celesteela": "铁火辉夜", "Kartana": "纸御剑",
    "Guzzlord": "恶食大王",
    "Necrozma": "奈克洛兹玛",
    "Marshadow": "玛夏多",
    "Poipole": "毒贝比", "Naganadel": "四颚针龙",
    "Blacephalon": "砰头小丑", "Stakataka": "垒磊石",
    "Zeraora": "捷拉奥拉",
    
    # Gen 8
    "Grookey": "敲音猴", "Thwackey": "轰擂金刚猩", "Rillaboom": "轰擂金刚猩",
    "Scorbunny": "炎兔儿", "Raboot": "腾蹴小将", "Cinderace": "闪焰王牌",
    "Sobble": "泪眼蜥", "Drizzile": "变涩蜥", "Inteleon": "千面避役",
    "Skwovet": "贪心栗鼠", "Greedent": "藏饱栗鼠",
    "Rookidee": "稚山雀", "Corvisquire": "蓝鸦", "Corviknight": "钢铠鸦",
    "Nickit": "偷儿狐", "Thievul": "狐大盗",
    "Gossifleur": "棉孢子", "Eldegoss": "白蓬蓬",
    "Wooloo": "毛辫羊", "Dubwool": "毛辫羊",
    "Chewtle": "咬咬龟", "Drednaw": "咬咬龟",
    "Yamper": "来电汪", "Boltund": "逐电犬",
    "Rolycoly": "小炭仔", "Carkol": "大炭车", "Coalossal": "巨炭山",
    "Applin": "啃果虫", "Flapple": "苹裹龙", "Appletun": "丰蜜龙",
    "Silicobra": "沙包蛇", "Sandaconda": "沙螺蟒",
    "Cramorant": "古月鸟",
    "Arrokuda": "刺梭鱼", "Barraskewda": "穿梭梭鱼",
    "Toxel": "电电虫", "Toxtricity": "颤弦蝾螈",
    "Sizzlipede": "焚烬虫", "Centiskorch": "火神蜈蚣",
    "Clobbopus": "拳拳蛸", "Grapploct": "八爪武师",
    "Sinistea": "来悲茶", "Polteageist": "来悲粗茶",
    "Hatenna": "迷布莉姆", "Hattrem": "布莉姆温", "Hatterene": "布莉姆温",
    "Impidimp": "捣蛋小妖", "Morgrem": "诡计妖", "Grimmsnarl": "长毛巨魔",
    "Obstagoon": "堵拦熊",
    "Perrserker": "喵头目",
    "Cursola": "魔灵珊瑚",
    "Sirfetch'd": "大葱鸭",
    "Mr. Rime": "踏冰人偶",
    "Runerigus": "死神板",
    "Milcery": "小鲜奶", "Alcremie": "霜奶仙",
    "Falinks": "列阵兵",
    "Pincurchin": "海胆兄弟",
    "Snom": "雪吞虫", "Frosmoth": "雪绒蛾",
    "Stonjourner": "巨石丁",
    "Eiscue": "冰砌鹅",
    "Indeedee": "爱管侍",
    "Morpeko": "莫鲁贝可",
    "Cufant": "铜象", "Copperajah": "巨锻匠",
    "Dracozolt": "雷鸟龙", "Arctozolt": "雷鸟冰龙",
    "Dracovish": "鳃鱼龙", "Arctovish": "鳃鱼冰龙",
    "Duraludon": "铝钢龙",
    "Dreepy": "多龙梅西亚", "Drakloak": "多龙奇", "Dragapult": "多龙巴鲁托",
    "Zacian": "苍响", "Zamazenta": "藏玛然特",
    "Eternatus": "无极汰那",
    "Kubfu": "熊徒弟", "Urshifu": "武道熊师",
    "Zarude": "萨戮德",
    "Regieleki": "雷吉艾勒奇", "Regidrago": "雷吉多拉戈",
    "Glastrier": "雪暴马", "Spectrier": "灵幽马",
    "Calyrex": "蕾冠王",
    
    # Gen 9
    "Sprigatito": "新叶喵", "Floragato": "蒂蕾喵", "Meowscarada": "魔幻假面喵",
    "Fuecoco": "呆火鳄", "Crocalor": "炙烫鳄", "Skeledirge": "骨纹巨声鳄",
    "Quaxly": "润水鸭", "Quaxwell": "涌跃鸭", "Quaquaval": "狂欢浪舞鸭",
    "Lechonk": "爱吃豚", "Oinkologne": "飘香豚",
    "Tarountula": "圆丝蛛", "Spidops": "操丝蛛",
    "Nymble": "跳出蟋蟀", "Lokix": "赫拉克罗斯",
    "Pawmi": "布拨", "Pawmo": "布土拨", "Pawmot": "布土拨",
    "Tandemaus": "一对鼠", "Maushold": "一家鼠",
    "Fidough": "狗仔包", "Dachsbun": "大电狗",
    "Smoliv": "迷你芙", "Dolliv": "奥利纽", "Arboliva": "奥利瓦",
    "Squawkabilly": "怒鹦哥",
    "Nacli": "盐石", "Naclstack": "盐石垒", "Garganacl": "盐石巨灵",
    "Charcadet": "炭小侍", "Armarouge": "红莲铠骑", "Ceruledge": "苍炎刃鬼",
    "Tadbulb": "电蝌蚪", "Bellibolt": "电肚蛙",
    "Wattrel": "电海燕", "Kilowattrel": "大电海燕",
    "Maschiff": "黑仔犬", "Mabosstiff": "獒教父",
    "Shroodle": "涂标客", "Grafaiai": "涂标客",
    "Bramblin": "草丛鬼", "Brambleghast": "草丛鬼",
    "Toedscool": "真菌菇", "Toedscruel": "真假菌",
    "Klawf": "毛崖蟹",
    "Capsakid": "辣椒仔", "Scovillain": "火辣辣椒",
    "Rellor": "滚蚂蚱", "Rabsca": "虫虫服务",
    "Flittle": "飘飘雏", "Espathra": "超能鸵鸟",
    "Tinkatink": "小锻匠", "Tinkatuff": "巧锻匠", "Tinkaton": "巨锻匠",
    "Wiglett": "海地鼠", "Wugtrio": "三海地鼠",
    "Bombirdier": "炸弹头",
    "Finizen": "波普海豚", "Palafin": "波普海豚",
    "Varoom": "嗡嗡蟋", "Revavroom": "轰鸣月",
    "Cyclizar": "爬地翅", "Orthworm": "拖拖蚓",
    "Glimmet": "晶光芽", "Glimmora": "晶光花",
    "Greavard": "墓仔狗", "Houndstone": "墓扬犬",
    "Flamigo": "火烈鸟",
    "Kecleon": "变色龙",
    "Tatsugiri": "米立龙",
    "Annihilape": "弃世猴",
    "Clodsire": "乌栗",
    "Farigiraf": "奇麒麟",
    "Dudunsparce": "土龙节节",
    "Kingambit": "仆刀将军",
    "Great Tusk": "古鼎鹿",
    "Scream Tail": "吼叫尾",
    "Brute Bonnet": "猛恶菇",
    "Flutter Mane": "振翼发",
    "Slither Wing": "爬翅飞蛾",
    "Sandy Shocks": "沙铁皮",
    "Iron Treads": "铁碾迹",
    "Iron Bundle": "铁包袱",
    "Iron Hands": "铁臂膀",
    "Iron Jugulis": "铁脖颈",
    "Iron Moth": "铁火蛾",
    "Iron Thorns": "铁荆棘",
    "Frigibax": "冻脊龙", "Arctibax": "冻脊龙", "Baxcalibur": "戟脊龙",
    "Glimmet": "晶光芽", "Glimmora": "晶光花",
    "Bombirdier": "炸弹头",
    "Orthworm": "拖拖蚓",
    "Tinkaton": "巨锻匠",
    "Wugtrio": "三海地鼠",
    "Revavroom": "轰鸣月",
    "Cyclizar": "爬地翅",
    "Pawmot": "布土拨",
    "Rabsca": "虫虫服务",
    "Espathra": "超能鸵鸟",
    "Grafaiai": "涂标客",
    "Brambleghast": "草丛鬼",
    "Toedscruel": "真假菌",
    "Scovillain": "火辣辣椒",
    "Rabsca": "虫虫服务",
    "Houndstone": "墓扬犬",
    "Palafin": "波普海豚",
    "Revavroom": "轰鸣月",
    "Flamigo": "火烈鸟",
    "Tatsugiri": "米立龙",
    "Annihilape": "弃世猴",
    "Clodsire": "乌栗",
    "Farigiraf": "奇麒麟",
    "Dudunsparce": "土龙节节",
    "Kingambit": "仆刀将军",
    "Baxcalibur": "戟脊龙",
    "Gholdengo": "赛富豪",
    "Wo-Chien": "古简蜗",
    "Chien-Pao": "古剑豹",
    "Ting-Lu": "古鼎鹿",
    "Chi-Yu": "古玉鱼",
    "Koraidon": "故勒顿",
    "Miraidon": "密勒顿",
    "Walking Wake": "轰吼月",
    "Gouging Fire": "炽焰咆哮",
    "Raging Bolt": "雷鸣咆哮",
    "Iron Leaves": "铁毒蛾",
    "Dipplin": "裹蜜虫",
    "Poltchageist": "来悲茶",
    "Sinistcha": "来悲粗茶",
    "Okidogi": "够赞狗",
    "Munkidori": "愿增猿",
    "Fezandipiti": "吉雉鸡",
    "Ogerpon": "厄诡椪",
    "Archaludon": "铝钢桥龙",
    "Hydrapple": "蜜集大蛇",
    "Giraffe": "奇麒麟",
    "Raging Bolt": "雷鸣咆哮",
    "Gouging Fire": "炽焰咆哮",
    "Walking Wake": "轰吼月",
    "Iron Leaves": "铁毒蛾",
    "Terapagos": "太乐巴戈斯",
    "Pecharunt": "桃歹郎",
}

# Common move Chinese names
MOVE_CN = {
    "Thunderbolt": "十万伏特", "Thunder": "打雷",
    "Ice Beam": "冰冻光束", "Blizzard": "暴风雪",
    "Flamethrower": "喷射火焰", "Fire Blast": "大字爆炎",
    "Surf": "冲浪", "Hydro Pump": "水炮",
    "Earthquake": "地震", "Earth Power": "大地之力",
    "Psychic": "精神强念", "Psyshock": "精神击破",
    "Shadow Ball": "暗影球",
    "Dragon Claw": "龙爪", "Dragon Pulse": "龙息",
    "Dark Pulse": "恶之波动",
    "Flash Cannon": "加农光炮",
    "Energy Ball": "能量球", "Leaf Storm": "飞叶风暴",
    "Stone Edge": "岩崩", "Rock Slide": "岩崩",
    "X-Scissor": "十字剪", "Bug Buzz": "虫鸣",
    "Poison Jab": "毒击", "Sludge Bomb": "垃圾射击",
    "Close Combat": "近身战", "Focus Blast": "真气弹",
    "Brave Bird": "勇鸟猛攻", "Hurricane": "暴风",
    "Play Rough": "嬉闹",
    "Iron Head": "铁头", "Iron Tail": "铁尾",
    "Stealth Rock": "隐形岩", "Spikes": "撒菱",
    "Toxic": "剧毒", "Will-O-Wisp": "鬼火",
    "Swords Dance": "剑舞", "Dragon Dance": "龙之舞",
    "Calm Mind": "冥想", "Nasty Plot": "诡计",
    "Protect": "守住", "Substitute": "替身",
    "Sucker Punch": "突袭", "Knock Off": "拍落",
    "U-turn": "急速折返", "Volt Switch": "伏特替换",
    "Flip Turn": "快速折返",
    "Aqua Jet": "水之波动",
    "Extreme Speed": "神速",
    "Bullet Punch": "子弹拳",
    "Ice Shard": "冰冻拳",
    "Mach Punch": "音速拳",
    "Fake Out": "击掌奇袭",
    "Taunt": "挑拨",
    "Thunder Wave": "电磁波",
    "Encore": "再来一次",
    "Rapid Spin": "高速旋转",
    "Defog": "清除浓雾",
    "Roost": "羽栖",
    "Synthesis": "光合作用",
    "Moonlight": "月光",
    "Rest": "睡觉",
    "Sleep Talk": "梦话",
    "Toxic Spikes": "毒菱",
    "Light Screen": "光墙",
    "Reflect": "反射壁",
    "Trick Room": "戏法空间",
    "Rain Dance": "求雨",
    "Sunny Day": "大晴天",
    "Snowscape": "雪景",
    "Endeavor": "拼尽全力",
    "Final Gambit": "孤注一掷",
    "Heal Bell": "治愈铃声",
    "Aromatherapy": "芳香治疗",
    "Wish": "祈愿",
    "Foul Play": "欺诈",
    "Phantom Force": "暗影潜袭",
    "Outrage": "逆鳞",
    "Flare Blitz": "闪焰冲锋",
    "Wood Hammer": "木槌",
    "Head Smash": "双刃头锤",
    "Gunk Shot": "垃圾射击",
    "Megahorn": "超级角击",
    "Power Whip": "强力鞭打",
    "Leaf Blade": "叶刃",
    "Night Slash": "暗袭要害",
    "Psycho Cut": "精神利刃",
    "Air Slash": "空气斩",
    "Aura Sphere": "波导弹",
    "Stored Power": "辅助力量",
    "Expanding Force": "广域战力",
    "Draining Kiss": "吸取之吻",
    "Dazzling Gleam": "魔法闪耀",
    "Bitter Malice": "凄凄暴风雪",
    "Ruination": "灾祸之渊",
    "Make It Rain": "淘金潮",
    "Astral Barrage": "灵魂骇客",
    "Glaive Rush": "巨兽斩",
    "Bleakwind Storm": "枯叶风暴",
    "Wildbolt Storm": "鸣雷风暴",
    "Sandsear Storm": "热沙风暴",
    "Lumina Crash": "精神噪音",
    "Chloroblast": "光子喷涌",
    "Mountain Gale": "冰山风",
    "Victory Star": "胜利之星",
    "Fillet Away": "甩肉",
    "Population Bomb": "万碎虫",
    "Revival Blessing": "复兴祈祷",
    "Shed Tail": "断尾",
    "Jet Punch": "喷射拳",
    "Barb Barrage": "毒刺射击",
    "Infernal Parade": "地狱遍历",
    "Triple Arrows": "三连箭",
    "Matcha Gocha": "抹茶招打",
    "Syrop Bomb": "焦糖炸弹",
    "Salt Cure": "盐腌",
    "Comeuppance": "报应",
    "Armor Cannon": "铠农炮",
    "Headlong Rush": "突贯禅",
    "Mountain Gale": "冰山风",
    "Esper Wing": "念力翼",
    "Torch Song": "灼热之歌",
    "Aqua Step": "水之舞步",
    "Flower Trick": "花式恶作剧",
    "Psyblade": "精神刃",
    "Hydro Steam": "水蒸气",
    "Supercell Slam": "超级电光",
    "Electro Drift": "电光漂移",
    "Doppelganger": "替身攻击",
    "Blood Moon": "血月",
    "Vine Whip": "藤鞭",
    "Tackle": "撞击",
    "Scratch": "抓",
    "Ember": "火花",
    "Water Gun": "水枪",
    "Razor Leaf": "飞叶快刀",
    "Vine Whip": "藤鞭",
    "Leech Seed": "寄生种子",
    "Poison Powder": "毒粉",
    "Stun Spore": "麻痹粉",
    "Sleep Powder": "催眠粉",
    "Solar Beam": "日光束",
    "Fire Fang": "火焰牙",
    "Thunder Fang": "雷电牙",
    "Ice Fang": "冰冻牙",
    "Bite": "咬住",
    "Crunch": "咬碎",
    "Iron Defense": "铁壁",
    "Body Press": "扑击",
    "Heavy Slam": "重磅冲击",
    "Gyro Ball": "陀螺球",
    "Autotomize": "轻金属化",
    "Metal Sound": "金属音",
    "Screech": "刺耳声",
    "Slash": "劈开",
    "Slash": "劈开",
    "Wing Attack": "翅膀攻击",
    "Fly": "飞翔",
    "Bounce": "弹跳",
    "Acrobatics": "杂技",
    "Tailwind": "顺风",
    "Sky Attack": "神鸟猛击",
    "Brave Bird": "勇鸟猛攻",
    "Drill Peck": "钻头直击",
    "Peck": "啄",
    "Fury Attack": "乱突",
    "Horn Attack": "角撞",
    "Megahorn": "超级角击",
    "Horn Drill": "角钻",
    "Take Down": "猛撞",
    "Double-Edge": "舍身冲撞",
    "Return": "报恩",
    "Frustration": "迁怒",
    "Facade": "硬撑",
    "Giga Impact": "终极冲击",
    "Hyper Beam": "破坏光线",
    "Quick Attack": "电光一闪",
    " Agility": "高速移动",
    "Growl": "叫声",
    "Leer": "瞪眼",
    "Smokescreen": "烟幕",
    "Confuse Ray": "奇异光线",
    "Scary Face": "恐吓",
    "Swift": "高速星星",
    "Dizzy Punch": "迷昏拳",
    "Super Fang": "必杀门牙",
    "Crunch": "咬碎",
    "Bite": "咬住",
    "Headbutt": "头突",
    "Body Slam": "泰山压顶",
}

def main():
    # Save Pokemon CN mapping
    with open(os.path.join(DATA_DIR, "pokemon_cn.json"), "w") as f:
        json.dump(POKEMON_CN, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(POKEMON_CN)} Pokemon Chinese names")
    
    # Save Move CN mapping
    with open(os.path.join(DATA_DIR, "moves_cn.json"), "w") as f:
        json.dump(MOVE_CN, f, indent=2, ensure_ascii=False)
    print(f"Saved {len(MOVE_CN)} move Chinese names")

if __name__ == "__main__":
    main()
